version: "3.9"

services:
  ds-service:
    build:
      context: ./ds-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  sentiment-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DS_SERVICE_BASE_URL: http://ds-service:8000
    depends_on:
      - ds-service
